apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-chat-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    repoURL: https://github.com/kushal9897/app-to-chat.git
    targetRevision: HEAD
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
